modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/nat212/steppy/issues"
license = "MIT"

[[mods]]
modId = "steppy"
version = "${version}"
displayName = "Steppy"
authors = "Natasha Draper"
description = '''
Take the big steppy you've always dreamed of!
'''
logoFile = "assets/steppy/icon.png"

[[dependencies.steppy]]
modId = "neoforge"
type = "required"
versionRange = "[21.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.steppy]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.steppy]]
modId = "cloth-config"
type = "required"
versionRange = "[18,)"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "steppy.mixins.json"
